### ISSUE TITLE
Support for Google Analytics 4

### ISSUE THREAD

**Issue by awsaf49** [fastai/fast_template#56]
In **Google Analytics 4** there is no tracking id (UA-XXXXXX-X) rather we have Measurement ID. When we use it inf `_config.yml` it doesn't track data. According to this issue (jekyll/minima#561), it's jekyll issue. Three is a mention of a solution [here](https://github.com/jekyll/minima/issues/561#issuecomment-748793956),
```diff
# _config.yml

- theme: minima
+ remote_theme: jekyll/minima

  plugins:
+ - jekyll-remote-theme
```
But if we try it we get a build error in `assets/main.scss` with the following msg,
```yml
      Layout source: theme
         Rendering: assets/main.scss
  Pre-Render Hooks: assets/main.scss
  Rendering Liquid: assets/main.scss
  Rendering Markup: assets/main.scss
github-pages 227 | Error:  File to import not found or unreadable: minima.
Load paths:
  /usr/local/bundle/gems/jekyll-theme-primer-0.6.0/_sass
  /tmp/jekyll-remote-theme-20220715-10-15anlab/_sass on line 1
      Remote Theme: Cleaning up /tmp/jekyll-remote-theme-20220715-10-15anlab
```
